## Регистрация пользователя
POST http://localhost:3010/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Алексей",
  "email": "ma@ma.ru",
  "password": "111111"
}

###

## Авторизация пользователя
POST http://localhost:3010/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "mabori@mail.ru",
  "password": "381392"
}

###

## Проверка токена пользователя
GET http://localhost:3010/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hYm9yaUBtYWlsLnJ1IiwiaWQiOiI2NTE0M2FlNDcyZjgyZjc5MjZmNTQ5Y2YiLCJpYXQiOjE2OTYwNzI0NzUsImV4cCI6MTY5NjI0NTI3NX0.MJnWC7yrST3vPTskMKkSw-qXI4zIZKPyQn1PH2htaU8

###
